### ISSUE TITLE
Timestamps shown with incorrect timezone

### ISSUE THREAD

**Issue by zuk** [adparlor/conduit#2]
Timestamp values are shown with the server's timezone. For example, "2015-07-24 13:00:00 -0500". This is incorrect since timestamps are in UTC, so this should be "2015-07-24 13:00:00 UTC". Maybe less confusing to just drop the timezone and show the time value as "2015-07-24 13:00:00"?

**Comment by zuk** [comment]
Ah nevermind, looks like the output is correct. The timezone shown is the node's timezone.

**Comment by AnthonyBobsin** [comment]
Should I still drop the timezone, or is it ok to close this issue?

**Comment by zuk** [comment]
It's probably fine as is but I need to get a better understanding of how the ruby driver deals with timestamps. I think there might still some funny stuff going on in there, so might as well keep open for now.
